name: celest_cli
description: The command-line interface for Celest.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  analyzer: ^6.3.0
  args: ^2.4.2
  async: ^2.11.0
  aws_common: ^0.6.1
  built_collection: ^5.1.1
  built_value: ^8.6.3
  celest:
    path: ../../packages/celest
  celest_cli_common:
    path: ../../packages/celest_cli_common
  celest_rpc:
    path: ../../packages/celest_rpc
  code_builder: ^4.8.0
  collection: ^1.18.0
  dart_style: ^2.3.4
  fixnum: ^1.1.0
  functions_framework: ^0.4.3+1
  http: ^1.1.2
  json_annotation: ^4.8.1
  mason_logger: ^0.2.10
  meta: ^1.11.0
  path: ^1.8.3
  pubspec_parse: ^1.2.3
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  shelf_web_socket: ^1.0.4
  stream_transform: ^2.1.0
  watcher: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.6
  build_version: ^2.1.1
  built_value_generator: ^8.8.0
  celest_lints:
    path: ../../packages/celest_lints
  json_serializable: ^6.7.1
  test: ^1.24.0
  test_descriptor: ^2.0.1

executables:
  celest:
