name: celest_cli
description: The command-line interface for Celest.
version: 0.2.0-dev.4
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  analyzer: ^6.3.0
  archive: ^3.4.9
  args: ^2.4.2
  async: ^2.11.0
  aws_common: ^0.6.1
  built_collection: ^5.1.1
  built_value: ^8.6.3
  celest:
    path: ../../celest/packages/celest
  celest_cli_common:
    path: ../../packages/celest_cli_common
  celest_core:
    path: ../../celest/packages/celest_core
  celest_proto:
    path: ../../packages/celest_proto
  cli_script: ^1.0.0
  code_builder: ^4.8.0
  collection: ^1.18.0
  convert: ^3.1.1
  crypto: ^3.0.3
  dart_style: ^2.3.4
  drift: ^2.14.1
  file: ^7.0.0
  fixnum: ^1.1.0
  functions_framework: ^0.4.3+1
  http: ^1.1.2
  json_annotation: ^4.8.1
  logging: ^1.2.0
  mason_logger: ^0.2.10
  meta: ^1.10.0
  os_detect: ^2.0.1
  package_config: ^2.1.0
  path: ^1.8.3
  platform: ^3.1.3
  process: ^5.0.1
  pub_semver: ^2.1.4
  pub_server:
    path: ../../packages/pub_server
  pubspec_parse: ^1.2.3
  sentry: ^7.14.0
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  shelf_web_socket: ^1.0.4
  source_span: ^1.10.0
  sqlite3:
    path: ../../packages/sqlite3/sqlite3
  stream_transform: ^2.1.0
  uuid: ^4.3.1
  vm_service: ^14.0.0
  watcher: ^1.1.0
  yaml: ^3.1.2
  yaml_edit: ^2.1.1

dependency_overrides:
  built_value: ^8.9.0
  celest:
    path: ../../celest/packages/celest
  celest_cli_common:
    path: ../../packages/celest_cli_common
  celest_core:
    path: ../../celest/packages/celest_core
  celest_proto:
    path: ../../packages/celest_proto
  # Use vendored sqlite3 to make use of native-assets
  sqlite3:
    path: ../../packages/sqlite3/sqlite3

dev_dependencies:
  build: ^2.4.1
  build_runner: ^2.4.7
  build_test: ^2.2.1
  build_version: ^2.1.1
  built_value_generator: ^8.8.0
  celest_lints:
    path: ../../packages/celest_lints
  checks: ^0.3.0
  chunked_stream: ^1.4.2
  drift_dev: ^2.14.1
  gcloud: ^0.8.12
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.2
  mustache_template: ^2.0.0
  test: ^1.24.9
  test_descriptor: ^2.0.1

executables:
  celest:
