name: celest_cli
description: The command-line interface for Celest.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  args: ^2.4.2
  async: ^2.11.0
  aws_common: ^0.6.1
  mason_logger: ^0.2.10
  path: ^1.8.3
  pubspec_parse: ^1.2.3
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  shelf_web_socket: ^1.0.4
  celest:
    path: ../../packages/celest

dev_dependencies:
  celest_lints:
    path: ../../packages/celest_lints
  test: ^1.24.0

executables:
  celest:
