name: celest_cli
description: The command-line interface for Celest.
version: 0.4.7
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  # TODO: Cannot use latest because type system uses `identical` in subtype checks instead of `==`
  # https://github.com/dart-lang/sdk/commit/f82ab4c6eaf0ebb6f3e85de6ce323b04250be700
  analyzer: <6.5.0
  analyzer_plugin: ^0.11.3
  api_celest:
    path: ../../packages/api_celest
  archive: ^3.4.9
  args: ^2.4.2
  async: ^2.11.0
  aws_common: ^0.6.1
  built_collection: ^5.1.1
  built_value: ^8.6.3
  cedar:
    path: ../../cedar/packages/cedar
  cedar_ffi:
    path: ../../cedar/packages/cedar_ffi
  celest:
    path: ../../celest/packages/celest
  celest_auth:
    path: ../../celest/packages/celest_auth
  celest_cli_common:
    path: ../../packages/celest_cli_common
  celest_core:
    path: ../../celest/packages/celest_core
  chunked_stream: ^1.4.2
  cli_script: ^1.0.0
  code_builder: ^4.8.0
  collection: ^1.18.0
  convert: ^3.1.1
  corks_cedar: ^0.1.0
  crypto: ^3.0.3
  dart_style: ^2.3.4
  drift: ^2.16.0
  email_validator: ^2.1.17
  file: ^7.0.0
  fixnum: ^1.1.0
  functions_framework: ^0.4.3+1
  html2md: ^1.3.1
  http: ^1.1.2
  http_parser: ^4.0.2
  hub:
    path: ../../services/hub
  json_annotation: ^4.9.0
  lib_openapi:
    path: ../../packages/lib_openapi
  libcoder: ^0.0.1
  logging: ^1.2.0
  mason_logger: ^0.2.10
  meta: ^1.10.0
  native_assets_builder: ^0.6.1
  native_assets_cli: ^0.5.4
  os_detect: ^2.0.1
  package_config: ^2.1.0
  path: ^1.8.3
  platform: ^3.1.3
  process: ^5.0.1
  protobuf: ^3.1.0
  pub_semver: ^2.1.4
  pub_server:
    path: ../../packages/pub_server
  pubspec_parse: ^1.2.3
  sentry: ^7.14.0
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  shelf_web_socket: ^2.0.0
  source_span: ^1.10.0
  sqlite3:
    path: ../../packages/sqlite3/sqlite3
  stack_trace: ^1.11.1
  stream_channel: ^2.1.2
  stream_transform: ^2.1.0
  uuid: ^4.3.1
  vm_service: ^14.0.0
  watcher: ^1.1.0
  yaml: ^3.1.2
  yaml_edit: ^2.1.1

dependency_overrides:
  api_celest:
    path: ../../packages/api_celest
  built_value: ^8.9.0
  cedar:
    path: ../../cedar/packages/cedar
  cedar_ffi:
    path: ../../cedar/packages/cedar_ffi
  celest:
    path: ../../celest/packages/celest
  celest_auth:
    path: ../../celest/packages/celest_auth
  celest_cli_common:
    path: ../../packages/celest_cli_common
  celest_core:
    path: ../../celest/packages/celest_core

  # TODO: Remove aws_common dependency
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

  # Use vendored sqlite3 to make use of native-assets
  sqlite3:
    path: ../../packages/sqlite3/sqlite3

dev_dependencies:
  benchmark_harness: ^2.2.2
  build: ^2.4.1
  build_runner: ^2.4.7
  build_test: ^2.2.1
  built_value_generator: ^8.8.0
  celest_lints:
    path: ../../packages/celest_lints
  checks: ^0.3.0
  drift_dev: ^2.14.1
  gcloud: ^0.8.12
  # Required for the `gcloud` package
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  json_serializable: ^6.8.0
  mocktail: ^1.0.2
  mustache_template: ^2.0.0
  test: ^1.24.9
  test_descriptor: ^2.0.1

executables:
  celest:
