name: celest_cli
description: The command-line interface for Celest.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  args: ^2.4.2
  async: ^2.11.0
  aws_common: ^0.6.1
  celest:
    path: ../../packages/celest
  celest_cli_common:
    path: ../../packages/celest_cli_common
  celest_rpc:
    path: ../../packages/celest_rpc
  mason_logger: ^0.2.10
  path: ^1.8.3
  pubspec_parse: ^1.2.3
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  shelf_web_socket: ^1.0.4
  watcher: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.6
  build_version: ^2.1.1
  celest_lints:
    path: ../../packages/celest_lints
  test: ^1.24.0

executables:
  celest:
